### PR TITLE
[neptune] Update submodules

### PR DESCRIPTION
**Pull request by mathias-baumann-sociomantic**
This PR has been automatically created by *neptune-autopr* and
updates the following submodules:

* **makd** from version **v1.7.3** to version **v1.11.2** ([Release notes](https://github.com/sociomantic-tsunami/makd/releases/tag/v1.11.2), [Changed commits](https://github.com/sociomantic-tsunami/makd/compare/v1.7.3...v1.11.2))

You can modify this behavior using your `.neptune.yml` file
as described in the [documentation](https://github.com/sociomantic-tsunami/neptune/blob/master/doc/neptune-metadata.rst#automatic-update-prs).

 This is an experimental feature. Please provide any feedback or problems you
 notice to the #core-team slack channel or as issues in the neptune repository.

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
Something is wrong with d1to2fix submodules and I would hate to touch it :/

**Comment by nemanja-boric-sociomantic** [comment]
It's just that it's using beaver that's not tagged (`Upgrade beaver to devel branch HEAD for v3`). Updating `beaver` to released v3 should fix it.

**Comment by nemanja-boric-sociomantic** [comment]
I had the same problem locally trying to build d1to2fix.

**Comment by mihails-strasuns-sociomantic** [comment]
Closing in favor of https://github.com/sociomantic-tsunami/d1to2fix/pull/26

**Pull request closed without merging**
