### PR TITLE
[neptune] Update makd to v1.11.2

### PR DESCRIPTION
**Pull request by mathias-baumann-sociomantic**
This PR has been automatically created by neptune-autopr and updates submodule makd from version v1.7.3 to version v1.11.2

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
@mathias-baumann-sociomantic no such hash :(

**Comment by mathias-baumann-sociomantic** [comment]
But it's right there: https://github.com/sociomantic-tsunami/beaver/commit/f3a4dd0d6f7932af463aa573ec2318728ed1b832

**Comment by mathias-baumann-sociomantic** [comment]
Also, this PR didn't even touch beaver.. this is a travis problem

**Comment by mathias-baumann-sociomantic** [comment]
```
error: Server does not allow request for unadvertised object f3a4dd0d6f7932af463aa573ec2318728ed1b832
Fetched in submodule path 'submodules/beaver', but it did not contain f3a4dd0d6f7932af463aa573ec2318728ed1b832. Direct fetching of that commit failed.
```

**Comment by mathias-baumann-sociomantic** [comment]
Superceeded by https://github.com/sociomantic-tsunami/d1to2fix/pull/23

**Pull request closed without merging**
